Feature/NEX-1529/remove test preview dependency
oat-sa/extension-tao-test pull request #348
Opened 2020-08-26 08:30 UTC by bziondik

2020-08-26 10:33 UTC, jsconan requested changes
Instead of hardcoding the load, you should rely on a backend registry instead.
This is especially bad here as there is a link from a generic extension to an implementation-specific extension.

Please take a look at how the item previewer is managed. Even if not perfect, it is still better.

2020-08-26 10:33 UTC, jsconan commented on views/js/controller/tests/action.js
> +            }
typo in names:

```suggestion
            previewers: {
                id: 'qtiTests',
                module: 'taoQtiTestPreviewer/previewer/adapter/test/qtiTest',
                bundle: 'taoQtiTestPreviewer/loader/qtiPreviewer.min',
                category: 'previewers'
            }
```

2020-08-26 10:33 UTC, jsconan commented on views/js/controller/tests/action.js
> +            feedback().error('Test Preview is not installed, please contact to your administrator.');
```suggestion
            feedback().error('Test Preview is not installed, please contact your administrator.');
```

2020-08-26 13:14 UTC, bziondik commented
@Alroniks can you check CI errors in PHP unit tests?

2020-08-26 17:06 UTC, jsconan reviewed
The overall idea is ok.
Please be careful to not introduce links with a specific implementation, like with the name of the provider.
To manage the providers, a similar approach to what has been done for the item previewer might be considered: https://github.com/oat-sa/extension-tao-item/blob/8d9724086e0f2558a5bb8aea9529bf0d36211831/models/classes/preview/ItemPreviewerService.php#L36

Otherwise, a better approach would be to follow the same pattern as for the test runner, but will be a lot more complex as it would require to refactor the controller. The TR providers are managed in a [dedicated registry](https://github.com/oat-sa/extension-tao-test/blob/c757b902a0c9301b2cf4e34f48f124b6a67c05d1/models/classes/runner/providers/ProviderRegistry.php#L33).

Anyway, in both cases the important thing to retain is an API is supplied to manage the registry, avoiding other extensions to directly manipulate it, with risks of corruption.

2020-08-27 08:02 UTC, bziondik commented
@jsconan The configuration will be handled in a separate ticket

2020-08-27 08:23 UTC, habemuscode commented
Manifest version?

2020-08-27 09:16 UTC, habemuscode approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful
- [x] Pull request's target is not `master`

2020-08-27 12:27 UTC, jsconan approved these changes
Looks good, despite unit tests for the new factory are not added.
Will need a rework to properly handle the previewer instead of hardcoding the name.

**Review Checklist**
- [ ] New code is covered by tests (if applicable)
- [x] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [x] Pull request title and description are meaningful

2020-08-27 12:32 UTC, merged