update version @oat-sa/tao-test-runner
oat-sa/extension-tao-test pull request #354
Opened 2020-09-16 12:18 UTC by bziondik

2020-09-22 15:14 UTC, btamas approved these changes

2020-09-23 11:50 UTC, wazelin requested changes

2020-09-23 11:50 UTC, wazelin commented on views/build/grunt/paths.json
> +    "taoItems/assets": "../../../taoTests/views/node_modules/@oat-sa/tao-item-runner/dist/assets"
```suggestion
    "taoTests/runner": "../node_modules/@oat-sa/tao-test-runner/dist",
    "taoItems/runner": "../node_modules/@oat-sa/tao-item-runner/dist/runner",
    "taoItems/assets": "../node_modules/@oat-sa/tao-item-runner/dist/assets"
```

2020-09-23 12:00 UTC, wazelin approved these changes
- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [x] New code is respecting code style rules
- [x] New code is respecting best practices
- [x] New code is not subject to concurrency issues (if applicable)
- [ ] Feature is working correctly on my local machine (if applicable)
- [x] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful ⚠️ would be nice to have a clear indication of what that update brings
- [x] Pull request's target is not `master`

2020-09-24 16:32 UTC, krampstudio approved these changes

2020-09-24 16:32 UTC, merged