[Fix] Translation metadata not persisted in datastore
oat-sa/extension-tao-test pull request #486
Opened 2024-11-20 09:02 UTC by shpran

# [ADF-1828](https://oat-sa.atlassian.net/browse/ADF-1828)

## Changes
* Translation lists type changed from System Object to List
* Translation list marked as non-editable in RDF

2024-11-20 10:14 UTC, gabrielfs7 commented on migrations/Version202411200904162363_taoTests.php
> +        OntologyUpdater::syncModels();
- [ ] Lets remove this migration, please. It will not be needed anymore.

2024-11-20 10:16 UTC, gabrielfs7 commented on models/ontology/taotest.rdf
> +    <generis:is_editable rdf:resource="http://www.tao.lu/Ontologies/generis.rdf#False"/>
I do not get why this property is special and needs this new `is_editable` attribute. It was never the case in TAO until now, why inventing this?

2024-11-20 12:42 UTC, gabrielfs7 commented on composer.json
> +        "oat-sa/generis": "dev-fix/adf-1828/translation-data-in-datastore as 99.99",
- [ ] @shpran Please, revert the generis change

```suggestion
        "oat-sa/generis": ">=15.39.0",
```

2024-11-20 12:43 UTC, gabrielfs7 commented on models/ontology/taotest.rdf
> +    <generis:is_editable rdf:resource="http://www.tao.lu/Ontologies/generis.rdf#False"/>
- [ ] @shpran Lets not forget to remove this property here, please

```suggestion
```

2024-11-20 12:43 UTC, gabrielfs7 requested changes
Please, fix the comments. Thank you!

2024-11-21 07:48 UTC, gabrielfs7 approved these changes
Looks good, thanks @shpran

- [ ] New code is covered by tests (if applicable)
- [ ] Tests are running successfully (old and new ones) on my local machine (if applicable)
- [ ] New code is respecting code style rules
- [ ] New code is respecting best practices
- [ ] New code is not subject to concurrency issues (if applicable)
- [x] Feature is working correctly on my local machine (if applicable)
- [ ] Acceptance criteria are respected
- [ ] Pull request title and description are meaningful

2024-11-22 11:07 UTC, shpran commented on composer.json
> +        "oat-sa/tao-core": "dev-fix/adf-1828/translation-data-in-datastore as 99.99",
- [ ] Change before merge

2024-11-22 13:55 UTC, merged